[versions]
asciidoctorj = "3.0.1"                  # https://github.com/asciidoctor/asciidoctorj/releases
asciidoctorj-pdf = "2.3.23"             # https://github.com/asciidoctor/asciidoctorj-pdf/releases
buildConfig = "6.0.9"                   # https://github.com/gmazzo/gradle-buildconfig-plugin/releases
compose = "1.11.0"                      # https://github.com/JetBrains/compose-multiplatform/releases
cup = "1.0.0-Beta-17"                   # https://github.com/KodeinKoders/CuP/releases
emoji = "2.4.0"                         # https://github.com/kosi-libs/Emoji.kt/releases
kotlin = "2.3.21"                       # https://github.com/jetbrains/kotlin/releases
material3 = "1.11.0-alpha07"            # https://github.com/JetBrains/compose-multiplatform/releases
materialIcons = "1.7.3"                 # https://github.com/JetBrains/compose-multiplatform/releases
qrose = "1.1.2"                         # https://github.com/alexzhirkevich/qrose/releases
resourceFiles = "1.0.0"                 # https://github.com/KodeinKoders/gradle-resource-files/releases

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
resourceFiles = { id = "net.kodein.gradle.resources.resource-files", version.ref = "resourceFiles" }

[libraries]
asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
asciidoctorj-pdf = { module = "org.asciidoctor:asciidoctorj-pdf", version.ref = "asciidoctorj-pdf" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIcons" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
cup = { module = "net.kodein.cup:cup", version.ref = "cup" }
cup-widgets-material3 = { module = "net.kodein.cup:cup-widgets-material3", version.ref = "cup" }
cup-sourceCode = { module = "net.kodein.cup:cup-widgets-source-code", version.ref = "cup" }
cup-plugin-imageExport = { module = "net.kodein.cup:cup-plugin-image-export", version.ref = "cup" }
cup-plugin-key-events = { module = "net.kodein.cup:cup-plugin-key-events", version.ref = "cup" }
cup-plugin-laser = { module = "net.kodein.cup:cup-plugin-laser", version.ref = "cup" }
cup-plugin-overview = { module = "net.kodein.cup:cup-plugin-overview", version.ref = "cup" }
cup-plugin-speakerWindow = { module = "net.kodein.cup:cup-plugin-speaker-window", version.ref = "cup" }
cup-plugin-window-management = { module = "net.kodein.cup:cup-plugin-window-management", version.ref = "cup" }
emoji-compose = { module = "org.kodein.emoji:emoji-compose-m2", version.ref = "emoji" }
gradlePlugin-resourceFiles = { module = "net.kodein.gradle.resources.resource-files:net.kodein.gradle.resources.resource-files.gradle.plugin", version.ref = "resourceFiles" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }

[bundles]
compose = [
    "compose-components-resources",
    "compose-runtime",
    "compose-foundation",
    "compose-material3",
    "compose-material-icons",
]
cup = [
    "cup",
    "cup-widgets-material3",
    "cup-sourceCode",
    "cup-plugin-imageExport",
    "cup-plugin-key-events",
    "cup-plugin-laser",
    "cup-plugin-overview",
    "cup-plugin-speakerWindow",
    "cup-plugin-window-management",
]
